---
title: "p8105_hw2_mt3866"
output: github_document
---

First, load the tidyverse library

```{r}
library(tidyverse)
```

Importing the data sets we are using

```{r}
pols_df =
  read_csv("fivethirtyeight_datasets/pols-month.csv")

unemployment_df =
  read_csv("fivethirtyeight_datasets/unemployment.csv")

snp_df =
  read_csv("fivethirtyeight_datasets/snp.csv")

```

Clean names in pols-months data set, separate into year month and day, make year and day integers while month is a character word. Now, remove prez_dem prez_gop and the day variable, and make a president variable taking values gop and dem.

```{r}
pols_df=
    read_csv("fivethirtyeight_datasets/pols-month.csv") |>
    janitor::clean_names() |>
    separate(mon, into = c("year", "month", "day"), sep = "-") |>
    mutate(
      year = as.integer(year),
      month = as.integer(month),
      day = as.integer(day),
      month = month.name[month]
    ) |>
  mutate(president = prez_dem + prez_gop
         ) 
  pols_df = select(pols_df, -day, -prez_dem, -prez_gop)
```





